name: Update Notion Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5  * * * *"
  workflow_dispatch:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-database:
    env:
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    runs-on: ubuntu-20.04
    steps:
      - name: set time zone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: Install curl
        run: sudo apt-get install curl
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Use Notion API client
        run: npm install @notionhq/client
      - name: Install dependencies
        run: npm ci
      - name: Run JS scripts
        run: |
          node totalPrice.js
          node expensive_expenses.js
          node spent_on_food.js
      - name: Update Issue
        run: |
          total_price=$(node totalPrice.js | grep "Total price:" | sed "s/Total price://g" | xargs)
          expensive_count=$(node expensive_expenses.js | grep "Number of expensive expenses:" | sed "s/Number of expensive expenses://g" | xargs)
          food_amount=$(node spent_on_food.js | grep "Total amount spent on food:" | sed "s/Total amount spent on food://g" | xargs)
          nonfood_amount=$(echo "$total_price - $food_amount" | bc)
          curl -H "Authorization: token ${{ secrets.G_T }}" \
            -X PATCH https://api.github.com/repos/lesnolie/jizhang/issues/28 \
            -d '{"title":"Monthly expense report","body":"Total price: '$total_price'\nNumber of expensive expenses: '$expensive_count'\nTotal amount spent on food: '$food_amount'\nTotal amount spent on non-food items: '$nonfood_amount'"}'
# 注意修改你自己的issue地址
