name: Update Notion Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-database:
    env:
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        run: sudo apt-get install curl
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Use Notion API client
        run: npm install @notionhq/client
      - name: Install dependencies
        run: npm ci
      - name: Run fetchNotionData.js
        run: npm run fetch-data
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      - name: Create New Issue
        run: |
          curl -H "Authorization: token ${{ secrets.G_T }}" \
               -X POST https://api.github.com/repos/lesnolie/jizhang/issues \
               -d '{"title":"New issue with total price","body":"Total price: '$(node fetchNotionData.js | grep "Total price:" | sed "s/Total price://g" | xargs)'"}'

