name: Fetch Notion Data

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ main ]

env:
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Fetch data and save to file
        run: node fetchNotionData.js
        env:
          NOTION_DATABASE_ID: ${{ env.NOTION_DATABASE_ID }}
          NOTION_API_KEY: ${{ env.NOTION_API_KEY }}
      - name: Commit data file
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update data.json"
          git push
