name: Update Notion Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-database:
    env:
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        run: sudo apt-get install curl
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Use Notion API client
        run: npm install @notionhq/client
      - name: Install dependencies
        run: npm ci
      - name: Run fetchNotionData.js
        run: npm run fetch-data
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      - name: Create New Issue
        run: |
          total_price=$(node fetchNotionData.js | grep "Total price:" | sed "s/Total price://g" | xargs)
          expensive_count=$(node fetchNotionData.js | grep "Number of expensive expenses:" | sed "s/Number of expensive expenses://g" | xargs)
          food_amount=$(node fetchNotionData.js | grep "Total amount spent on food:" | sed "s/Total amount spent on food://g" | xargs)
          nonfood_amount=$(node fetchNotionData.js | grep "Total amount spent on non-food items:" | sed "s/Total amount spent on non-food items://g" | xargs)
          curl -H "Authorization: token ${{ secrets.G_T }}" \
            -X POST https://api.github.com/repos/lesnolie/jizhang/issues \
            -d '{"title":"Monthly expense report","body":"Total price: '$total_price'\nNumber of expensive expenses: '$expensive_count'\nTotal amount spent on food: '$food_amount'\nTotal amount spent on non-food items: '$nonfood_amount'"}'
