name: Avoid Suspended
on:
    schedule:
        - cron: '0 8 */7 * *'
jobs:
    avoid:
        name: Avoid Github Action Suspended
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
          with:
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
        - name: Make commits
          run: |
              echo "avoid" >> avoid.txt
              git config --global user.name "Github Action"
              git config --global user.email "action@github.com"
              git add .
              git commit -m "Avoiding workflow being suspended."
              git push
