name: Update Notion Pages on Issue

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch:

jobs:
  update-issue:
    env:
      NOTION_DATABASE_JPID: ${{ secrets.NOTION_DATABASE_JPID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Use Notion API client
        run: npm install @notionhq/client axios # 添加 axios 到安装列表
      - name: Install dependencies
        run: npm ci
      - name: Run JS script
        run: node japaneseshengcibiao.js
      - name: Update Issue
        run: |
          output=$(cat output.txt)
          curl -H "Authorization: token ${{ secrets.G_T }}" \
            -X PATCH https://api.github.com/repos/lesnolie/jizhang/issues/30 \
            -d '{"title":"Japanese Vocabulary", "body":"'"$output"'"}'
